#!/bin/bash
# KITTYVONCAN Fabric Dashboard Launcher
# Spins up a structured kitty session for accelerator control/monitoring.

set -euo pipefail

KITTY_CONFIG_DIR="${KITTY_CONFIG_DIR:-$HOME/.config/kitty}"
KITTYVONCAN_DIR="$KITTY_CONFIG_DIR/kittyvoncan"
SESSION_DIR="$KITTYVONCAN_DIR/sessions"
SESSION_FILE="$SESSION_DIR/fabric_dashboard.session"

fabric_workdir="${KITTY_FABRIC_WORKDIR:-$KITTYVONCAN_DIR}"
fabricctl_cmd="${FABRICCTL_CMD:-fabricctl status --watch}"
gpu_monitor_cmd="${GPU_MONITOR_CMD:-intel_gpu_top}"
npu_status_cmd="${NPU_STATUS_CMD:-watch -n 2 npu-status}"
system_monitor_cmd="${SYSTEM_MONITOR_CMD:-htop}"
openvino_bench_cmd="${OPENVINO_BENCH_CMD:-ov-bench --live}"
gateway_cmd="${GATEWAY_CMD:-python ./local_llm_gateway.py}"
npu_log_cmd="${NPU_LOG_CMD:-journalctl -fu openvino-npu.service}"
metrics_cmd="${METRICS_CMD:-curl -N http://localhost:9100/metrics | grep -E \"npu|gpu|llm\"}"
dmesg_cmd="${DMESG_CMD:-dmesg -w | egrep \"intel_vpu|GNA|thunderbolt|Arc\"}"
device_ls_cmd="${DEVICE_LS_CMD:-ls /dev/accel* /dev/dri/*}"
guardian_cmd="${GUARDIAN_CMD:-milspec-guardian --tui}"
thermal_cmd="${THERMAL_CMD:-tb monitor}"
ipython_cmd="${IPYTHON_CMD:-ipython}"
fabric_cli_cmd="${FABRIC_CLI_CMD:-python ./fabric_cli.py}"

escape_for_single_quotes() {
    printf "%s" "$1" | sed "s/'/'\"'\"'/g"
}

warn_missing_commands() {
    local -a commands=(
        "$fabricctl_cmd"
        "$gpu_monitor_cmd"
        "$npu_status_cmd"
        "$system_monitor_cmd"
        "$openvino_bench_cmd"
        "$gateway_cmd"
        "$npu_log_cmd"
        "$metrics_cmd"
        "$dmesg_cmd"
        "$device_ls_cmd"
        "$guardian_cmd"
        "$thermal_cmd"
        "$ipython_cmd"
        "$fabric_cli_cmd"
    )

    local -a missing=()
    local binary

    for command_string in "${commands[@]}"; do
        binary=$(printf "%s\n" "$command_string" | awk '{print $1}')
        if [[ -n "$binary" ]] && ! command -v "$binary" >/dev/null 2>&1; then
            missing+=("$binary")
        fi
    done

    if [[ ${#missing[@]} -gt 0 ]]; then
        echo "Warning: missing commands detected: ${missing[*]}"
        echo "Edit $SESSION_FILE or set environment overrides (e.g., FABRICCTL_CMD) to match your stack."
    fi
}

write_default_session() {
    mkdir -p "$SESSION_DIR"

    cat > "$SESSION_FILE" <<EOF
# KITTYVONCAN Fabric Dashboard Session
# Generated by fabric_dashboard.sh; edit to suit your stack.

new_tab Fabric Control
cd "$fabric_workdir"
launch --type=window bash -lc '$(escape_for_single_quotes "$fabricctl_cmd") || { echo "fabricctl missing; set FABRICCTL_CMD or edit this session."; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$gpu_monitor_cmd") || { echo "intel_gpu_top missing (install intel-gpu-tools)"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$npu_status_cmd") || { echo "npu-status missing; set NPU_STATUS_CMD"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$system_monitor_cmd") || { echo "htop missing; install htop"; exec bash; }'

new_tab AI Ops
cd "$fabric_workdir"
launch --type=window bash -lc '$(escape_for_single_quotes "$openvino_bench_cmd") || { echo "ov-bench missing; set OPENVINO_BENCH_CMD"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$gateway_cmd") || { echo "Update GATEWAY_CMD to your gateway entrypoint"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$npu_log_cmd") || { echo "Adjust NPU_LOG_CMD for your service name"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$metrics_cmd") || { echo "Metrics endpoint missing; set METRICS_CMD"; exec bash; }'

new_tab MILSPEC
cd "$fabric_workdir"
launch --type=window bash -lc '$(escape_for_single_quotes "$dmesg_cmd") || { echo "No dmesg stream; set DMESG_CMD"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$device_ls_cmd") || { echo "Adjust DEVICE_LS_CMD for your device nodes"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$guardian_cmd") || { echo "milspec-guardian missing; set GUARDIAN_CMD"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$thermal_cmd") || { echo "Thermal/board monitor missing; set THERMAL_CMD"; exec bash; }'

new_tab Dev
cd "$fabric_workdir"
launch --type=window bash -lc '$(escape_for_single_quotes "$ipython_cmd") || { echo "ipython missing; set IPYTHON_CMD"; exec bash; }'
launch --type=window bash -lc '$(escape_for_single_quotes "$fabric_cli_cmd") || { echo "Adjust FABRIC_CLI_CMD to your CLI"; exec bash; }'
launch --type=window bash -lc 'bash'
EOF
}

main() {
    if ! command -v kitty >/dev/null 2>&1; then
        echo "kitty is not installed or not in PATH."
        exit 1
    fi

    mkdir -p "$SESSION_DIR"

    if [[ ! -f "$SESSION_FILE" ]]; then
        write_default_session
        echo "Created default fabric dashboard session at $SESSION_FILE"
    fi

    warn_missing_commands
    exec kitty --session "$SESSION_FILE"
}

main "$@"
